version: '3'
services:
  db:
    image: "postgres:9.6.5"
    ports:
      - "8081"
    networks:
      - db_nw
  nginx:
    image: "nginx:latest"
    ports:
      - "8080:80"
#    volumes:
#      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
